
import React, { useState, useEffect } from 'react';
import { User } from '../types';
import { userService } from '../services/userService';
import { authService } from '../services/authService';
import { translations, getAuthErrorMessage, type Language } from '../translations';
import Logo from './Logo';
import { User as UserIcon, Mail, Phone, Lock, ArrowRight, ArrowLeft, CheckCircle, RefreshCcw } from 'lucide-react';
import { useToast } from './ToastProvider';

interface RegisterCustomerProps {
  onRegister: (user: User) => void;
  onBackToLogin: () => void;
}

const RegisterCustomer: React.FC<RegisterCustomerProps> = ({ onRegister, onBackToLogin }) => {
  const lang: Language = (typeof document !== 'undefined' && (document.documentElement.lang === 'ar' || document.documentElement.lang === 'en' || document.documentElement.lang === 'he')) ? document.documentElement.lang as Language : 'ar';
  const t = translations[lang];
  const { showToast } = useToast();
  const isRtl = lang !== 'en';

  // State Machine: FORM -> VERIFY
  const [step, setStep] = useState<'FORM' | 'VERIFY'>('FORM');
  const [verificationCode, setVerificationCode] = useState('');
  const [emailNotSent, setEmailNotSent] = useState(false);

  const [formData, setFormData] = useState({
    name: '',
    email: '',
    phone: '',
    password: '',
    confirmPassword: ''
  });
  
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
    if (error) setError('');
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    // Validation
    if (!formData.name || !formData.email || !formData.password || !formData.phone) {
      const msg = lang === 'ar' ? 'جميع الحقول مطلوبة' : lang === 'he' ? 'כל השדות חובה' : 'All fields are required';
      setError(msg);
      showToast(msg, 'warning');
      setLoading(false);
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      const msg = lang === 'ar' ? 'كلمات المرور غير متطابقة' : lang === 'he' ? 'הסיסמאות אינן תואמות' : 'Passwords do not match';
      setError(msg);
      showToast(msg, 'error');
      setLoading(false);
      return;
    }

    const newUser: User = {
      id: '', // Generated by service
      name: formData.name,
      email: formData.email,
      phone: formData.phone,
      role: 'CUSTOMER',
      status: 'PENDING',
      isApproved: false,
      createdAt: Date.now(),
    };

    const result = await userService.register(newUser, formData.password);

    if (result.success && result.data) {
      const msg =
        lang === 'ar'
          ? 'تم إنشاء حساب الزبون بنجاح. تم إرسال رمز تحقق إلى بريدك الإلكتروني – يرجى تأكيد بريدك ثم تسجيل الدخول.'
          : lang === 'he'
          ? 'חשבון הלקוח נוצר בהצלחה. נשלח קוד אימות לאימייל שלך – אנא אמת ואז התחבר.'
          : 'Customer account created successfully. A verification code was sent to your email – please verify and then log in.';
      showToast(msg, 'success');
      if (typeof window !== 'undefined') {
        window.location.hash = '#/login';
      }
    } else {
      const msg = getAuthErrorMessage(result.error || 'Registration failed', lang);
      setError(msg);
      showToast(msg, 'error');
    }
    setLoading(false);
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    const result = await userService.verifyEmail(formData.email, verificationCode);
    if (result.success && result.data) {
      showToast(lang === 'ar' ? 'تم تأكيد الحساب!' : lang === 'he' ? 'החשבון אומת!' : 'Account Verified!', 'success');
      const loginResult = await authService.login(formData.email, formData.password);
      if (loginResult.success && loginResult.data) {
        onRegister(loginResult.data.user);
      } else {
        onRegister(result.data.user);
      }
    } else {
      const errMsg = getAuthErrorMessage(result.error || 'Verification failed', lang);
      setError(errMsg);
      showToast(errMsg, 'error');
    }
    setLoading(false);
  };

  const handleResend = async () => {
    setLoading(true);
    const result = await userService.resendVerificationCode(formData.email);
    if (result.success) {
      showToast(lang === 'en' ? 'Code sent!' : 'تم إرسال الرمز!', 'success');
    } else {
      showToast(getAuthErrorMessage(result.error || 'Error', lang), 'error');
    }
    setLoading(false);
  };

  return (
    <div className="min-h-screen flex bg-white font-sans text-slate-900" dir={isRtl ? 'rtl' : 'ltr'}>
      
      {/* Left Side: Form */}
      <div className="w-full lg:w-1/2 flex flex-col justify-center p-8 sm:p-16 lg:p-24 relative z-10">
        <div className="max-w-md w-full mx-auto space-y-10 animate-in slide-in-from-bottom-8 duration-700">
          
          {step === 'FORM' ? (
            <>
              {/* Header */}
              <div className="space-y-3">
                <div className="inline-block mb-4" onClick={onBackToLogin}>
                   <Logo size="small" />
                </div>
                <h1 className="text-4xl font-black text-palma-navy tracking-tight leading-tight">
                  {lang === 'en' ? 'Create Account' : 'إنشاء حساب جديد'}
                </h1>
                <p className="text-slate-400 font-bold text-xs uppercase tracking-widest">
                  {t.auth.customerSubtitle}
                </p>
              </div>

              {/* Error Message */}
              {error && (
                <div className="p-4 bg-red-50 border border-red-100 text-red-600 text-xs font-bold rounded-2xl flex items-center gap-3 animate-in shake">
                  <span className="w-2 h-2 rounded-full bg-red-500 shrink-0" />
                  {error}
                </div>
              )}

              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Full name */}
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
                    {t.auth.name}
                  </label>
                  <div className="relative group">
                    <UserIcon className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 group-focus-within:text-palma-primary transition-colors" />
                    <input
                      required
                      type="text"
                      name="name"
                      className="w-full pl-12 pr-4 py-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm font-bold text-palma-navy focus:bg-white focus:border-palma-primary focus:ring-2 focus:ring-palma-primary/10 outline-none transition-all placeholder:text-slate-300"
                      placeholder={lang === 'en' ? 'Your full name' : 'الاسم الكامل'}
                      defaultValue={formData.name}
                      onChange={handleChange}
                    />
                  </div>
                </div>

                {/* Email */}
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
                    {t.auth.email}
                  </label>
                  <div className="relative group">
                    <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 group-focus-within:text-palma-primary transition-colors" />
                    <input
                      required
                      type="email"
                      name="email"
                      className="w-full pl-12 pr-4 py-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm font-bold text-palma-navy focus:bg-white focus:border-palma-primary focus:ring-2 focus:ring-palma-primary/10 outline-none transition-all placeholder:text-slate-300"
                      placeholder="name@example.com"
                      defaultValue={formData.email}
                      onChange={handleChange}
                    />
                  </div>
                </div>

                {/* Phone */}
                <div className="space-y-2">
                  <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
                    {t.auth.phone}
                  </label>
                  <div className="relative group">
                    <Phone className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 group-focus-within:text-palma-primary transition-colors" />
                    <input
                      required
                      type="tel"
                      name="phone"
                      className="w-full pl-12 pr-4 py-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm font-bold text-palma-navy focus:bg-white focus:border-palma-primary focus:ring-2 focus:ring-palma-primary/10 outline-none transition-all placeholder:text-slate-300"
                      placeholder="05x-xxxxxxx"
                      defaultValue={formData.phone}
                      onChange={handleChange}
                    />
                  </div>
                </div>

                {/* Passwords */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
                      {t.auth.password}
                    </label>
                    <div className="relative group">
                      <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 group-focus-within:text-palma-primary transition-colors" />
                      <input
                        required
                        type="password"
                        name="password"
                        className="w-full pl-12 pr-4 py-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm font-bold text-palma-navy focus:bg-white focus:border-palma-primary focus:ring-2 focus:ring-palma-primary/10 outline-none transition-all placeholder:text-slate-300"
                        placeholder="••••••••"
                        defaultValue={formData.password}
                        onChange={handleChange}
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400 px-1">
                      {lang === 'en' ? 'Confirm Password' : 'تأكيد كلمة المرور'}
                    </label>
                    <div className="relative group">
                      <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400 group-focus-within:text-palma-primary transition-colors" />
                      <input
                        required
                        type="password"
                        name="confirmPassword"
                        className="w-full pl-12 pr-4 py-4 rounded-2xl border border-slate-200 bg-slate-50 text-sm font-bold text-palma-navy focus:bg-white focus:border-palma-primary focus:ring-2 focus:ring-palma-primary/10 outline-none transition-all placeholder:text-slate-300"
                        placeholder="••••••••"
                        defaultValue={formData.confirmPassword}
                        onChange={handleChange}
                      />
                    </div>
                  </div>
                </div>

                <div className="pt-6 space-y-6">
                  <button 
                    type="submit" 
                    disabled={loading} 
                    className="w-full py-5 bg-palma-primary text-white rounded-2xl font-black uppercase text-[11px] tracking-widest shadow-xl shadow-soft hover:bg-emerald-800 hover:scale-[1.01] transition-all active:scale-[0.98] disabled:opacity-70 disabled:cursor-not-allowed flex items-center justify-center gap-3 group"
                  >
                    {loading ? (
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    ) : (
                      <>
                        {lang === 'en' ? 'Sign Up Now' : 'تسجيل الحساب'}
                        {isRtl ? <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" /> : <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />}
                      </>
                    )}
                  </button>

                  <button 
                    type="button" 
                    onClick={onBackToLogin} 
                    className="w-full text-center text-xs font-bold text-slate-400 hover:text-palma-navy transition-colors uppercase tracking-wider"
                  >
                    {t.common.back}
                  </button>
                </div>
              </form>
            </>
          ) : (
            /* VERIFICATION STEP */
            <div className="text-center animate-in fade-in zoom-in duration-500">
               <div className="w-20 h-20 bg-palma-primaryLight text-palma-primary rounded-full flex items-center justify-center mx-auto mb-6">
                  <Mail className="w-8 h-8" />
               </div>
               <h2 className="text-2xl font-black text-slate-900 mb-2">{lang === 'en' ? 'Verify Email' : 'تحقق من البريد الإلكتروني'}</h2>
               <p className="text-slate-500 text-sm mb-2">{lang === 'en' ? `We sent a code to ${formData.email}` : `أرسلنا رمزاً إلى ${formData.email}`}</p>
               {emailNotSent && (
                 <p className="mb-4 px-4 py-2 bg-amber-50 text-amber-800 text-sm rounded-xl border border-amber-200">
                   {lang === 'en' ? 'Email sending is not configured. Use the code below to verify.' : 'إرسال البريد غير مُعد. استخدم الرمز أدناه للتحقق.'}
                 </p>
               )}
               <form onSubmit={handleVerify} className="space-y-6 max-w-xs mx-auto">
                  <input 
                    autoFocus
                    required
                    type="text" 
                    maxLength={6}
                    className="w-full p-5 text-center text-2xl font-black tracking-[0.5em] rounded-2xl border-2 border-slate-200 focus:border-palma-primary outline-none transition-all placeholder:text-slate-200"
                    value={verificationCode}
                    onChange={e => setVerificationCode(e.target.value.replace(/[^0-9]/g, ''))}
                    placeholder="000000"
                  />
                  
                  {error && <p className="text-red-500 text-xs font-bold">{error}</p>}

                  <div className="flex flex-col gap-3">
                    <button type="submit" disabled={loading || verificationCode.length < 6} className="w-full py-4 bg-palma-primary text-white rounded-2xl font-black uppercase text-[11px] tracking-widest shadow-xl disabled:opacity-50 hover:bg-emerald-800 transition-all">
                       {loading ? t.common.loading : (lang === 'en' ? 'Verify & Login' : 'تأكيد ودخول')}
                    </button>
                    
                    <button type="button" onClick={handleResend} disabled={loading} className="w-full py-3 bg-white text-slate-400 border border-slate-200 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all">
                       {lang === 'en' ? 'Resend Code' : 'إعادة إرسال الرمز'}
                    </button>
                  </div>
               </form>

               <button onClick={() => setStep('FORM')} className="mt-8 text-xs font-bold text-slate-400 hover:text-palma-navy flex items-center justify-center gap-2 mx-auto">
                 <RefreshCcw className="w-3 h-3" /> {lang === 'en' ? 'Change Email' : 'تغيير البريد'}
               </button>
            </div>
          )}
        </div>
      </div>

      {/* Right Side: Visual (Desktop Only) */}
      <div className="hidden lg:block lg:w-1/2 relative overflow-hidden bg-palma-navy">
        <div className="absolute inset-0 bg-gradient-to-br from-palma-navy via-palma-navy to-palma-primary opacity-90 z-10" />
        <img 
          src="https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=2070&auto=format&fit=crop" 
          className="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-50 z-0"
          alt="Shopping Lifestyle"
        />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-20 text-center text-white space-y-8 max-w-lg">
           <div className="w-24 h-24 bg-white/10 backdrop-blur-md rounded-[2rem] flex items-center justify-center mx-auto border border-white/20 shadow-2xl">
              <span className="text-5xl">✨</span>
           </div>
           <div>
             <h2 className="text-5xl font-black tracking-tighter mb-4 leading-tight">
               {lang === 'en' ? 'Join the Exclusive Marketplace' : 'انضم إلى السوق الحصري'}
             </h2>
             <p className="text-white/70 text-sm font-medium leading-relaxed">
               {lang === 'en' 
                 ? 'Access thousands of premium products from top-rated local merchants.' 
                 : 'تمتع بالوصول إلى آلاف المنتجات المميزة من أفضل التجار المحليين.'}
             </p>
           </div>
        </div>
      </div>

    </div>
  );
};

export default RegisterCustomer;
